phenology/backend/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

__docformat__ = 'restructuredtext en'
from django.conf.urls import patterns

urlpatterns = patterns(
    '',
    # Examples:
)
# vim:set et sts=4 ts=4 tw=80:

phenology/backoffice/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__docformat__ = 'restructuredtext en'

from django.conf.urls import patterns, url
from backoffice import views
from django.core.urlresolvers import reverse_lazy
import os
base_path = os.path.join(os.path.dirname(__file__))

urls = patterns(
    '',
    # home
    url(r'^$', views.index, name='home'),

    # profile
    url(r'^profile', views.user_detail, name='profile'),
    url(r'^register', views.register_user, name='register'),

    # change password
    url(r'^password_change',
        'django.contrib.auth.views.password_change',
        {'template_name': base_path + '/templates/generic_form.html',
         'post_change_redirect': reverse_lazy('home')}),

    # change password
    url(r'^password_reset', views.password_reset, name="password_reset"),
    # authentification
    url(r'^login',
        'django.contrib.auth.views.login',
        {'template_name': base_path + '/templates/login_form.html'},
        name='login'),
    url(r'^logout',
        'django.contrib.auth.views.logout',
        {"next_page": reverse_lazy('home')},
        name='logout'),

    # snowing
    url(r'^area/(?P<area_id>\d+)/snowing/create$', views.snowing_detail,
        name='snowing-detail'),
    url(r'^area/(?P<area_id>\d+)/snowing/(?P<snowing_id>\d+)',
        views.snowing_detail,
        name='snowing-detail'),

    # area
    url(r'^area/create$', views.area_detail, name='area-detail'),
    url(r'^area/(?P<area_id>\d+)', views.area_detail, name='area-detail'),

    # individual
    url(r'^individual/create$', views.individual_detail,
        name='individual-detail'),
    url(r'^individual/(?P<ind_id>\d+)', views.individual_detail,
        name='individual-detail'),

    # survey
    url(r'^survey/create$', views.survey_detail, name='survey-detail'),
    url(r'^survey/(?P<pk>[\w-]+)/delete/',
    views.SurveyDelete.as_view(), name='entry_delete'),
    url(r'^survey/(?P<survey_id>\d+)', views.survey_detail,
        name='survey-detail'),

    # mysurveys
    url(r'^mysurveys', views.dashboard, name='my-surveys'),
    url(r'^get_species_list$', views.get_species_list, name='species-list'),
    url(r'^chart_surveys', views.chart_surveys, name="chart-surveys"),

    # mystudies
    url(r'^mystudies$', views.my_studies, name='my-studies'),

    # datatable
    url(r'^allsurveys$', views.all_surveys, name='all-surveys'),
    url(r'^getsurveys$', views.get_surveys, name='get-surveys'),

    # map
    url(r'^map_all_surveys$', views.map_all_surveys, name='map-surveys'),
    url(r'^search_surveys', views.search_surveys, name="search-surveys"),

    # viz
    url(r'^viz_all_surveys$', views.viz_all_surveys, name='viz-surveys'),
    url(r'^get_data_for_viz$', views.get_data_for_viz, name='viz-data'),
    url(r'^viz_area_surveys$', views.viz_area_surveys,
        name='viz-area-surveys'),
    url(r'^get_area_data$', views.get_area_data, name='area-data'),


    # export
    url(r'^export_surveys', views.export_surveys, name="export-survey"),
    url(r'^export_snowings', views.export_snowings, name="export-snowing"),

    # map
    url(r'^map_all_snowings$', views.map_all_snowings, name='map-snowings'),
    url(r'^search_snowings', views.search_snowings, name="search-snowings"),
    url(r'^viz_snowings$', views.viz_snowings, name='viz-snowings'),
    url(r'^get_area_snowings$', views.get_area_snowings,
        name='viz-area-snowings'),
    url(r'^map_viz$', views.map_viz, name='viz-map'),
)
# vim:set et sts=4 ts=4 tw=80:

phenology/phenology/urls.py
from django.conf.urls import patterns, include, url, static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from rest_framework import routers
from backend import views
from phenology import settings
from backoffice.urls import urls as backoffice_urls

admin.autodiscover()

router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)
router.register(r'areas', views.AreaViewSet)
router.register(r'species', views.SpeciesViewSet)
router.register(r'observers', views.ObserverViewSet)
router.register(r'individuals', views.IndividualViewSet)
router.register(r'surveys', views.SurveyViewSet)
# from backoffice.forms import AccountForm
# from registration.backends.simple.views import RegistrationView

urlpatterns = patterns(
    '',
    # Examples:

    # url(r'^accounts/', include('accounts.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',
        namespace='rest_framework')),
    url(r'^user_settings', views.user_settings, name='user_settings'),
    url(r'^user_surveys/(?P<pk>\d+)', views.SurveyDetail.as_view(),
        name='survey-detail'),
    url(r'^user_surveys', views.UserSurveyList.as_view(), name='user_surveys'),
    url(r'^user_snowcover/(?P<pk>\d+)', views.SnowCoverDetail.as_view(),
        name='snowcover-detail'),
    url(r'^user_snowcover', views.UserSnowCoverList.as_view(),
        name='user_snowcover'),
    url(r'^portail/', include(backoffice_urls)),
    url(r'^select2/', include('select2.urls')),
)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static.static(settings.MEDIA_URL,
                             document_root=settings.MEDIA_ROOT)

phenology/backoffice/forms.py
from django import forms
from backend import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext


class CreateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).\
                exclude(username=username).count():
            raise forms.ValidationError(ugettext('Already exists'))
        return email

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email',)


class SnowingForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'),
                           input_formats=('%d/%m/%Y',))

    class Meta:
        model = models.Snowing
        fields = ('height', 'observer', 'remark', 'area', 'date')
        widgets = {
            'remark': forms.Textarea(attrs={'rows': 4}),
        }


class ResetPasswordForm(forms.Form):
    email = forms.CharField(label='Email', max_length=100)

    def clean_email(self):
        email = self.cleaned_data['email']
        found = User.objects.filter(email=email).first()
        if not found:
            raise forms.ValidationError(_("User with this email doesnt exist"))
        return email


class AccountForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        # magic
        in_creation = True
        if (not kwargs.get('instance')):
            observer = models.Observer()
            observer.user = User()
            self.user = observer.user
        else:
            if kwargs.get('instance').id:
                in_creation = False
            kwargs["instance"].id
            self.user = kwargs['instance'].user
        user_kwargs = kwargs.copy()
        user_kwargs['instance'] = self.user
        key_order = []
        if in_creation:
            self.uf = CreateUserForm(*args, **user_kwargs)
            key_order += ['username']
            self.uf.fields['email'].required = True
        else:
            self.uf = UserForm(*args, **user_kwargs)

        # magic end

        super(AccountForm, self).__init__(*args, **kwargs)
        self.fields.update(self.uf.fields)
        self.initial.update(self.uf.initial)
        self.fields.keyOrder = key_order +\
            ['username', 'organism', 'email',
             'fonction', 'nationality',
             'codepostal',
             'category',
             'accept_policy', 'accept_email', 'accept_newsletter']

    # check if checkbox accept_policy is True
    def clean_accept_policy(self):
        accept_policy = self.cleaned_data.get('accept_policy')
        if not accept_policy:
            raise forms.ValidationError(_('Field required'))
        return accept_policy

    # check if checkbox accept_email is True
    def clean_accept_email(self):
        accept_email = self.cleaned_data.get('accept_email')
        if not accept_email:
            raise forms.ValidationError(_('Field required'))
        return accept_email

    def is_valid(self):
        # save both forms
        is_valid = super(AccountForm, self).is_valid()
        if(not self.uf.is_valid()):
            self.errors.update(self.uf.errors)
            is_valid = False
        return is_valid

    def save(self, *args, **kwargs):
        # save both forms
        instance = self.uf.save(*args, **kwargs)
        self.instance.user = instance
        return super(AccountForm, self).save(*args, **kwargs)

    class Meta:
        model = models.Observer
        exclude = ('user', 'is_crea', 'is_active', 'areas', 'date_inscription')
        # widgets = {
        #    'adresse': forms.Textarea(attrs={'rows': 2}),
        # }


class AreaAdminForm(forms.ModelForm):
    observers = forms.fields.MultipleChoiceField(
        choices=[(a.id, unicode(a)) for a in models.Observer.objects.all()])

    class Meta:
        model = models.Area

    def __init__(self, *args, **kwargs):
        super(AreaAdminForm, self).__init__(*args, **kwargs)
        if self.instance.pk:
            # if this is not a new object, we load related books
            self.initial['observers'] = self.instance.observer_set.\
                values_list('pk', flat=True)

    def save(self, *args, **kwargs):
        instance = super(AreaAdminForm, self).save(*args, **kwargs)
        if instance.pk:
            for observer in instance.observer_set.all():
                if observer not in self.cleaned_data['observers']:
                    # we remove books which have been unselected
                    instance.observer_set.remove(observer)
            for observer in self.cleaned_data['observers']:
                if observer not in instance.observer_set.all():
                    # we add newly selected books
                    instance.observer_set.add(observer)
        return instance


class AreaForm(forms.ModelForm):
    class Meta:
        model = models.Area
        exclude = ('species', 'polygone', 'codezone')
        widgets = {
            'remark': forms.Textarea(attrs={'rows': 4}),
        }


class SurveyForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(format='%d/%m/%Y'),
                           input_formats=('%d/%m/%Y',))

    class Meta:
        exclude = ('is_dead', 'status', 'comment')
        model = models.Survey
        widgets = {
            'remark': forms.Textarea(attrs={'rows': 4}),
            'individual': forms.HiddenInput(),
            'stage': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        instance = kwargs.get("instance")
        self.base_fields['stage'].queryset = instance.\
            individual.\
            species.\
            stage_set.filter(is_active=True).order_by("order")
        self.base_fields['stage'].label = _("Change stage")
        super(SurveyForm, self).__init__(*args, **kwargs)

    def clean_date(self):
        date = self.cleaned_data['date']
        surveys = models.Survey.objects.\
            filter(date__year=date.year,
                   individual=self.instance.individual,
                   stage=self.instance.stage)
        surveys_id = [s.id for s in surveys]
        if(self.instance.id not in surveys_id and surveys.count() > 0):
            raise forms.ValidationError(ugettext('There is already a survey '
                                                 'with same stage, '
                                                 'same individual '
                                                 'in %(year)s') % {"year": date.year})
        return date

    def save(self, commit=True):
        if(self.cleaned_data["answer"] in ("today", "before")):
            self.cleaned_data["answer"] = "isObserved"
        instance = super(SurveyForm, self).save(commit=False)
        instance.save()
        return instance


class CreateIndividualForm(forms.ModelForm):
    class Meta:
        exclude = ('is_dead',)
        model = models.Individual
        widgets = {
            'remark': forms.Textarea(attrs={'rows': 4}),
            'area': forms.HiddenInput()
        }

    def clean_name(self):
        data = self.cleaned_data['name']
        free = self.instance.area.individual_set.\
            exclude(id=self.instance.id).filter(name=data).count() == 0
        if not free:
            raise forms.ValidationError(
                _("This name is already found in your area"))
        return data


class IndividualForm(CreateIndividualForm):
    class Meta:
        exclude = ('area',)
        model = models.Individual
        widgets = {
            'remark': forms.Textarea(attrs={'rows': 4}),
        }


class ObserverForm(forms.ModelForm):
    class Meta:
        model = models.Observer

    def __init__(self, *args, **kwargs):
        super(ObserverForm, self).__init__(*args, **kwargs)

phenology/backoffice/templates/account_form.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}


{% block title %}
  {% trans 'Register' %}
{% endblock %}


{% block content %}
<div class="row table-row">
  <div class="col-md-12 table-col">
    <div class="row">
      <div class="col-xs-12">
        <form id="register_form" method="post" class="form-horizontal" role="form">
          {% csrf_token %}

          {% bootstrap_field form.username %}
          {% bootstrap_field form.email %}
          {% bootstrap_field form.organism %}
          {% bootstrap_field form.fonction %}
          {% bootstrap_field form.category %}
          {% bootstrap_field form.nationality %}
          {% bootstrap_field form.codepostal %}


          <div>
            <div class="checkbox required {% if form.errors.accept_policy %} has-error {% endif %}">
              <label>
                <input type="checkbox" required name="{{ form.accept_policy.html_name }}" id="{{ form.accept_policy.id_for_label }}"
                {% if form.instance.accept_policy %}checked{% endif %}>
                {% trans "accept_security_policy" %}
              </label>
            </div>
              <div class="checkbox required {% if form.errors.accept_email %} has-error {% endif %}">
                <label>
                  <input type="checkbox" required name="{{ form.accept_email.html_name }}" id="{{ form.accept_email.id_for_label }}"
                  {% if form.instance.accept_email %}checked{% endif %}>
                  {% trans "accept_contact_email" %}
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox" name="{{ form.accept_newsletter.html_name }}" id="{{ form.accept_newsletter.id_for_label }}"
                  {% if form.instance.accept_newsletter %}checked{% endif %}>
                  {% trans "accept_newsletter" %}
                </label>
              </div>
          </div>


          <br/>


          {% buttons %}
            <button type="submit" class="btn btn-primary btn-lg btn-block {% if form.errors %} disabled {% endif %}" >
              {% bootstrap_icon "tree-deciduous" %} {% trans 'Validate' %}
            </button>
          {% endbuttons %}
        </form>
      </div>
    </div>
  </div>

  <script type="text/javascript">

    /*$( document ).ready(function(){
      checkFormStatus();

      $('form :input').change(
      function(){
        checkFormStatus();
      });

      function form_is_invalid() {
        var formInValid = false;
        if ( ! $('input[name=accept_policy]').is(':checked') || ! $('input[name=accept_email]').is(':checked')) {
          formInValid = true;
        }
        return formInValid;
      }

      function checkFormStatus() {
        var form_invalid = form_is_invalid();
        if (form_invalid) {
          $(':submit').addClass('disabled');
        } else {
          $(':submit').removeClass('disabled');
        }
      }

    })*/

  </script>
{% endblock %}

phenology/backoffice/templates/all_surveys.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load staticfiles %}
{% load json_filters %}

{% block title %}{{ form.instance.name }}{% endblock %}

{% block content %}

{% load i18n %}

<div style="padding-bottom: 10px;">
      <a class="btn btn-default btn-sm" href="{% url 'export-survey' %}" ><i class="icon ion-document-text"></i> {% trans 'Export my surveys' %}</a>
      <a class="btn btn-default btn-sm" href="{% url 'export-snowing' %}" ><i class="icon ion-document-text"></i> {% trans 'Export my snowings' %}</a>
      <a class="btn btn-default btn-sm" href="{% url 'chart-surveys' %}" ><i class="icon ion-stats-bars"></i> {% trans 'Chart surveys' %}</a>
</div>

<div class="row  table-row">

  <table class="mytable">
    <thead>
      <tr>
        <th>
          id
        </th>
        <th>
          {% trans "date" %}
        </th>
        <th>
          {% trans "Area" %}
        </th>
        <th>
          {% trans "Species" %}
        </th>
        <th>
          {% trans "Individual" %}
        </th>
        <th>
          {% trans "Organism" %}
        </th>
        <th>
          {% trans "Stage" %}
        </th>
        <th>
          {% trans "Answer" %}
        </th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  <script type="text/javascript">

    $( document ).ready(function(){
      $(".mytable").dataTable({
        "serverSide": true,
        "ajax": {
          "url": "{% url 'get-surveys' %}",
        },
        "language": {
          "url": "{% static 'vendor/datatables/i18n/' %}{{ request.LANGUAGE_CODE }}.json"
        },
        "processing": true,
        "pageLength": 20,
        "columns": [
          { data: "id",
            visible: false },
          { data: "date" },
          { data: "area" },
          { data: "species" },
          { data: "individual"},
          { data: "organisms",
            visible: false },
          { data: "stage" },
          { data: "answer" },
        ],
        "order": [[ 1, "desc" ]]
      });
    });
  </script>
{% endblock %}

phenology/backoffice/templates/generic_form.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}

{% block content %}

<form method="post" style="max-width:500px;margin:auto;padding:10px;" class="form">
{% csrf_token %}

  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "tree-deciduous" %} {% trans 'Validate' %}
    </button>
  {% endbuttons %}
</form>

{% endblock %}

phenology/backoffice/templates/registration_done.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% endblock %}
{% block content %}
<div class="row  table-row">

  <div class=" col-xs-12 col-md-12 table-col">
	<p class="text-center">
	{% blocktrans %}We have sent you an email with the password. <br/> Please check your email.{% endblocktrans %}
	</p>
  </div>
 </div>
{% endblock %}

phenology/backoffice/templates/snowing.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load staticfiles %}
{% load json_filters %}

{% block title %}{{ form.instance.name }}{% endblock %}

{% block content %}
  <script type="text/javascript">
    var phenoclim = phenoclim || {};
    {% if form %}
      phenoclim.options = phenoclim.options || {};
      phenoclim.options.snowings = {{ snowings|jsonify|safe }};
    {% endif %}
  </script>

  <div class="row  table-row">

    <div class="col-md-12  table-col">
      {% buttons %}
        <a href="{% url 'my-surveys' %}" class="btn btn-default">
          {% trans "Back" %}
        </a>
      {% endbuttons %}
      <div class="row">
        <div class="col-xs-12 text-center">
          <h2>Enneigement</h2>
        </div>
      </div>
      <form method="post" class="form-horizontal" role="form">
        {% csrf_token %}
        {{ form.errors }}
        {% bootstrap_field form.height %}
        {{ form.observer.as_hidden }}
        {{ form.area.as_hidden }}
        {% bootstrap_field form.date layout='inline'%}
        {% bootstrap_field form.remark %}
        {{ form.area }}
        {% buttons %}
          <button type="submit" class="btn btn-primary btn-lg btn-block">
            {% bootstrap_icon "tree-deciduous" %} {% trans 'Validate' %}
          </button>
        {% endbuttons %}
      </form>
        <div class="row">
            <div class="col-xs-12 text-center">
                <h3>Saisies précédentes</h3>
                <ul style="list-style-type: none;">
                    {% for entry in last_five %}
                        <li>
                            <a href="{% url 'snowing-detail' entry.area.pk entry.pk %}">{{ entry }} -
                                {{ entry.date|date:"D d M Y" }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <a href="{% url "snowing-detail" area_id %}">Nouvelle saisie</a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
 $(".answer>.radio").on("click", function(event){
  var $input = $("input", $(this));
  $input.prop("checked", "checked");
  var input_value = $input.val();
  if(input_value=="today"){
    console.log("today");
  }
  else if(input_value=="before"){
    console.log("before");
  }
  return false;
 });
</script>

<script src="{% static 'vendor/pickadate.js/lib/picker.js' %}"></script>
<script src="{% static 'vendor/pickadate.js/lib/picker.date.js' %}"></script>
<script src="{% static 'vendor/pickadate.js/lib/picker.time.js' %}"></script>
<link rel="stylesheet" href="{% static 'vendor/pickadate.js/lib/themes/default.css' %}"></link>
<link rel="stylesheet" href="{% static 'vendor/pickadate.js/lib/themes/default.date.css' %}"></link>
{% with lang=LANGUAGE_CODE %}
  {% if lang != "en" %}
      <script src="{% static 'vendor/pickadate.js/lib/translations/' %}{{lang}}_{{lang|upper}}.js"></script>
  {% endif %}
{% endwith %}
<script type="text/javascript">
$( document ).ready(function() {

  window.iFrameResizer = {
    readyCallback: function(){
      if('parentIFrame' in window){
          setTimeout(function() {
            parentIFrame.sendMessage( { "positionScroll": 0 } );
          }, 0);
        }
      }
  }

  $.each(phenoclim.options.snowings, function(i, d){
    d.timestamp = +moment(d.date);
  });
  var cache_date;
  $('#id_date').pickadate({
    format: 'dd/mm/yyyy', 
    formatSubmit: 'dd/mm/yyyy',
    onStart: function(a, b, c){
      console.log("start")
      cache_date = this.component.item.select.pick;
    },
    onRender: function(a, b, c) {
      $.each(phenoclim.options.snowings, function(i, d){
        $(".picker [data-pick='" + d.timestamp + "']").addClass('snowing').attr("data-snowing", d.id);
      })
      console.log('Whoa.. rendered anew', a, b, c, this);
    }, 
    onSet: function(context, i) {
      $node = $(".picker [data-pick='" + context.select + "']");
      if($node.hasClass('snowing')){
        window.location.href = $node.attr("data-snowing");
      }
    },
    max: true})
});
</script>

{% endblock %}

phenology/backoffice/templates/survey.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %}{{ form.instance.name }}{% endblock %}
{% block content %}
  <div class="row  table-row">
    <div class="col-md-12  table-col">
      <div class="row">
        <div class="col-xs-12 text-center">
        <a href="{% url 'my-surveys' %}" class="btn btn-default">
          {% trans "Back" %}
        </a>
          <h2>{{ form.instance.stage.name }}</h2>
        </div>
      </div>
      <div class="row preview_pictures">
        <div class="col-xs-4 text-center">
          <img src="{% thumbnail form.instance.stage.picture_before 1000x1000 %}"></img>
          <div>{% trans 'before' %}</div>
        </div>
        <div class="col-xs-4 text-center current">
          <img src="{% thumbnail form.instance.stage.picture_current 1000x1000 %}"></img>
          <div>{% trans 'current' %}</div>
        </div>
        <div class="col-xs-4 text-center">
          <img src="{% thumbnail form.instance.stage.picture_after 1000x1000 %}"></img>
          <div>{% trans 'after' %}</div>
        </div>
      </div>
      <form method="post" class="form-horizontal" role="form">
        {% csrf_token %}
        <div class="form_group answer {% if form.errors.answer %} has-error {% endif %}">
          {% if form.errors.answer %}
          <span class="help-block">{{ form.errors.answer.as_text }}</span>
          {% endif %}
        <label>
          <div class="btn btn-block btn-lg btn-default radio left-block">
              <input type="radio" name="{{ form.answer.html_name }}" id="{{ form.answer.id_for_label }}" value="isObserved"
              {% if form.instance.answer == 'isObserved' %}checked{% endif %}>
              {% trans "isObserved" %}
          </div>
        </label>
        <label>
          <div class="btn btn-block btn-lg btn-default radio">
                <input type="radio" name="{{ form.answer.html_name }}" id="{{ form.answer.id_for_label }}" value="isLost"
                {% if form.instance.answer == 'isLost' %}checked{% endif %}>
                {% trans "isLost" %}
          </div>
        </label>
        <label>
          <div class="btn btn-block btn-lg btn-default radio">
                <input type="radio" name="{{ form.answer.html_name }}" id="{{ form.answer.id_for_label }}" value="isNever"
                {% if form.instance.answer == 'isNever' %}checked{% endif %}>
                {% trans "isNever" %}
          </div>
        </label>
        <label>
          <div class="btn btn-block btn-lg btn-default radio">
              <input type="radio" name="{{ form.answer.html_name }}" id="{{ form.answer.id_for_label }}" value="isPassed"
              {% if form.instance.answer == 'isPassed' %}checked{% endif %}>
              {% trans "isPassed" %}
          </div>
        </label>
      </div>
        <br/>

        {% bootstrap_field form.remark layout='inline' %}
        {% bootstrap_field form.individual %}

        <div class="form-group required {% if form.errors.date %} has-error {% endif %}">
          {{ form.date.label_tag }}
          <input class="form-control" id="id_date" name="date" required="required" type="date" data-value="{{ form.instance.date|date:'d/m/Y' }}" value="{{ form.instance.date }}"></input>
          {% if form.errors.date %}
          <span class="help-block">{{ form.errors.date.as_text }}</span>
          {% endif %}
        </div>

        {% bootstrap_field form.stage %}

        {% buttons %}
          <button type="submit" class="btn btn-primary btn-lg btn-block">
            {% bootstrap_icon "tree-deciduous" %} {% trans 'Validate' %}
          </button>
        {% endbuttons %}
      </form>

    </div>
</div>

<script src="{% static 'vendor/pickadate.js/lib/picker.js' %}"></script>
<script src="{% static 'vendor/pickadate.js/lib/picker.date.js' %}"></script>
<script src="{% static 'vendor/pickadate.js/lib/picker.time.js' %}"></script>
<link rel="stylesheet" href="{% static 'vendor/pickadate.js/lib/themes/default.css' %}"></link>
<link rel="stylesheet" href="{% static 'vendor/pickadate.js/lib/themes/default.date.css' %}"></link>
{% with lang=LANGUAGE_CODE %}
  {% if lang != "en" %}
      <script src="{% static 'vendor/pickadate.js/lib/translations/' %}{{lang}}_{{lang|upper}}.js"></script>
  {% endif %}
{% endwith %}
<script type="text/javascript">
$( document ).ready(function() {
  $('#id_date').pickadate({format: 'dddd d mmmm yyyy', formatSubmit: 'dd/mm/yyyy', max: true, hiddenName: true})

  window.iFrameResizer = {
    readyCallback: function(){
      if('parentIFrame' in window){
          setTimeout(function() {
            parentIFrame.sendMessage( { "positionScroll": 0 } );
          }, 0);
        }
      }
  }
});
</script>
{% endblock %}